### PR TITLE
Av handler download

### PR DESCRIPTION
**Pull request by shiro101010101**
just push without my notebook.
@zohrea

### CODE REVIEW

**Comment by shiro101010101** [comment]
Please merge and double check: 
I created class in audio_downloader.py

**Comment by shiro101010101** [comment]
@zohrea 
Sorry I committed a lot. 

These are correct
-audio_downloader :added class (audio_downloader class 3)

-Audio-downloder-class_notebook: just note book for myself(final ver added notebook audio class downloder)

*Mistakenly I wrote "calss AVhandler.py as my comment",
Actually  I just added class in "audio_downloader.py"

**Comment by zoeyazimi** [comment]
Thanks @shiro101010101, looking great. I have just follow-up question, can you tell me what is this file for? .python-version
And the other one is about  "audio/cocktail_effect-run", I guess now we should put that in the scripts folder, not sure though.
The last part is about the AVHandelr.py, I think we already have one in the "data" folder", I don;t see any specific difference between the one already on master branch and this new one. If that's so can you remove this, so, we don't have a copy of the same file in two different folders.

**Comment by shiro101010101** [comment]
-python ver :when I tried to pull from your master, file was conflicted with my branch and I just corrected from  lewagon →cocktail_effect which much with your master.

-AVHandelr.py: Yes, Nothing change.I have a question before I remove.
If I removed the file from my folder, it caused some problems when I want to merge again? 

My branch: no AV handler.py
Master: AV handler.py

-cocktail_effect-run
I will remove from my audio folder.

**Pull request merged**
